-- Initial Supabase schema for a new ResQ-Flow project.
-- Existing tables are left untouched; apply 001_integration_safety.sql next.

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE RESTRICT,
    role text NOT NULL CHECK (role IN ('VICTIM', 'RESCUER', 'ADMIN')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
    name text NOT NULL,
    message text NOT NULL,
    latitude double precision,
    longitude double precision,
    timestamp timestamptz,
    people_count integer NOT NULL DEFAULT 1 CHECK (people_count > 0),
    disaster_type text,
    severity text CHECK (
        severity IS NULL OR
        severity IN ('LOW', 'MODERATE', 'HIGH', 'CRITICAL')
    ),
    priority_score integer CHECK (
        priority_score IS NULL OR priority_score BETWEEN 0 AND 100
    ),
    priority_reasons jsonb,
    analysis_method text,
    machine_learning_used boolean,
    ai_confidence numeric CHECK (
        ai_confidence IS NULL OR ai_confidence BETWEEN 0 AND 1
    ),
    status text NOT NULL DEFAULT 'NEW' CHECK (
        status IN ('NEW', 'ASSIGNED', 'RESCUE_IN_PROGRESS', 'RESCUED')
    ),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT incidents_coordinate_pair CHECK (
        (latitude IS NULL) = (longitude IS NULL)
    ),
    CONSTRAINT incidents_latitude_range CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT incidents_longitude_range CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

CREATE TABLE IF NOT EXISTS public.resources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL CHECK (
        type IN ('AMBULANCE', 'RESCUE_TEAM', 'MEDICAL_TEAM', 'SHELTER', 'FOOD', 'WATER')
    ),
    latitude double precision,
    longitude double precision,
    available boolean NOT NULL DEFAULT false,
    contact text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT resources_coordinate_pair CHECK (
        (latitude IS NULL) = (longitude IS NULL)
    ),
    CONSTRAINT resources_latitude_range CHECK (
        latitude IS NULL OR latitude BETWEEN -90 AND 90
    ),
    CONSTRAINT resources_longitude_range CHECK (
        longitude IS NULL OR longitude BETWEEN -180 AND 180
    )
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.profiles, public.incidents, public.resources
    FROM anon, authenticated;
GRANT ALL ON public.profiles, public.incidents, public.resources
    TO service_role;

DO $$
DECLARE
    sequence_name text;
BEGIN
    FOREACH sequence_name IN ARRAY ARRAY[
        'incidents_id_seq',
        'resources_id_seq'
    ] LOOP
        IF to_regclass('public.' || sequence_name) IS NOT NULL THEN
            EXECUTE format(
                'GRANT USAGE, SELECT ON SEQUENCE public.%I TO service_role',
                sequence_name
            );
        END IF;
    END LOOP;
END
$$;
